"""Split one upstream mark into the two cards it has to land on, three ways.

Some project marks are drawn for a light background and disappear on a dark one
— Portainer's is a black P, which on this dashboard's dark card is nothing at
all. Upstream ships a second drawing for those, and Homepage cannot pick
between two files by theme: it renders a tile icon as an <img>, which is its own
document and cannot see the page.

This writes three files from the two drawings:

    <name>-on-light.svg   the drawing for a light card, alone
    <name>-on-dark.svg    the drawing for a dark card, alone
    <name>.svg            both, switched by `prefers-color-scheme`

The pair is what the dashboard actually uses: config/custom.css points the tile
at one or the other by `data-theme`, which follows Homepage's own theme. The
combined file is the fallback for a browser that will not replace an <img> from
CSS — it answers the OS instead, which is right only while the OS and the
dashboard agree, and the dashboard is pinned to dark. Naming is by the card the
drawing goes ON, not by upstream's own suffix: upstream's `portainer-dark` is
the drawing *for* a dark background, and `open-webui-light` likewise, so the two
suffixes mean opposite things across the set.

Ids are prefixed on the way in, because the two drawings are usually the same
file with different fills and collide otherwise.

Driven by scripts/update-tile-icons.sh; not useful on its own.
"""

import os
import re

def load(path, prefix):
    svg = open(path, encoding="utf-8").read()
    svg = re.sub(r"<\?xml.*?\?>", "", svg, flags=re.S)
    svg = re.sub(r"<!DOCTYPE.*?>", "", svg, flags=re.S)
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S)

    match = re.search(r"<svg\b([^>]*)>(.*)</svg\s*>", svg, flags=re.S)
    if not match:
        raise SystemExit(f"compose-icon: {path} does not look like an SVG")
    attrs, body = match.group(1), match.group(2)

    # Keep only what defines the drawing's own coordinate space and defaults;
    # width/height are dropped so the nested drawings fill the wrapper.
    kept = []
    for name in ("viewBox", "fill", "stroke", "preserveAspectRatio"):
        found = re.search(rf'\b{name}="([^"]*)"', attrs)
        if found:
            kept.append(f'{name}="{found.group(1)}"')

    ids = set(re.findall(r'\bid="([^"]+)"', body))
    for ident in sorted(ids, key=len, reverse=True):
        body = body.replace(f'id="{ident}"', f'id="{prefix}-{ident}"')
        body = body.replace(f"url(#{ident})", f"url(#{prefix}-{ident})")
        body = body.replace(f'href="#{ident}"', f'href="#{prefix}-{ident}"')

    body = "\n".join("    " + line.strip() for line in body.strip().splitlines() if line.strip())
    return " ".join(kept), body

light_attrs, light_body = load(os.environ["LIGHT"], "l")
dark_attrs, dark_body = load(os.environ["DARK"], "d")
viewbox = re.search(r'viewBox="([^"]*)"', light_attrs)
viewbox = viewbox.group(1) if viewbox else "0 0 24 24"

out = os.environ["OUT"]
stem = out[:-4] if out.endswith(".svg") else out


def write_single(path, ground, attrs, body):
    """One drawing, alone, with nothing in it that reads the viewer."""
    open(path, "w", encoding="utf-8").write(f"""<!--
  GENERATED by scripts/update-tile-icons.sh — do not edit.

  {os.environ['NAME']}, from {os.environ['SOURCE']}: the drawing meant for a
  {ground} card, on its own. config/custom.css picks between this and its pair
  by `data-theme`, which is Homepage's theme — the thing a media query in here
  could not see. So there is no media query in here: the page decides, and this
  file only draws.

  {os.path.basename(stem)}.svg is the fallback that still asks the OS.
-->
<svg xmlns="http://www.w3.org/2000/svg" {attrs} role="img" aria-label="{os.environ['NAME']}">
{body}
</svg>
""")


write_single(f"{stem}-on-light.svg", "light", light_attrs, light_body)
write_single(f"{stem}-on-dark.svg", "dark", dark_attrs, dark_body)

open(out, "w", encoding="utf-8").write(f"""<!--
  GENERATED by scripts/update-tile-icons.sh — do not edit.

  {os.environ['NAME']}, from {os.environ['SOURCE']}: its default drawing and its
  {os.environ['VARIANT']} variant in one file, switched by the viewer's colour
  scheme.

  This is the FALLBACK. The dashboard normally swaps the tile between the two
  -on-light / -on-dark files beside this one, from config/custom.css, by its own
  theme. Only a browser that will not replace an <img> from CSS gets this file's
  answer — and the OS is the wrong question: it is right only while the phone
  and the dashboard agree, and settings.yaml pins the dashboard to dark.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}" role="img" aria-label="{os.environ['NAME']}">
  <style>
    .on-dark {{ display: none; }}
    @media (prefers-color-scheme: dark) {{
      .on-light {{ display: none; }}
      .on-dark {{ display: inline; }}
    }}
  </style>
  <svg class="on-light" {light_attrs}>
{light_body}
  </svg>
  <svg class="on-dark" {dark_attrs}>
{dark_body}
  </svg>
</svg>
""")
