"""Compose one icon that works on a light *and* a dark card.

Some project marks are drawn for a light background and disappear on a dark one
— Portainer's is a black P, which on this dashboard's dark card is nothing at
all. Upstream ships a second drawing for those, and Homepage cannot pick
between two files by theme: it renders a tile icon as an <img>, which is its own
document and cannot see the page.

An SVG document *can* see the viewer's colour scheme, though. So both drawings
go in one file, each in a nested <svg> that keeps its own coordinate system, and
a media query shows one of them. Ids are prefixed on the way in, because the two
drawings are usually the same file with different fills and collide otherwise.

Driven by scripts/update-tile-icons.sh; not useful on its own.
"""

import os
import re

def load(path, prefix):
    svg = open(path, encoding="utf-8").read()
    svg = re.sub(r"<\?xml.*?\?>", "", svg, flags=re.S)
    svg = re.sub(r"<!DOCTYPE.*?>", "", svg, flags=re.S)
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S)

    match = re.search(r"<svg\b([^>]*)>(.*)</svg\s*>", svg, flags=re.S)
    if not match:
        raise SystemExit(f"compose-icon: {path} does not look like an SVG")
    attrs, body = match.group(1), match.group(2)

    # Keep only what defines the drawing's own coordinate space and defaults;
    # width/height are dropped so the nested drawings fill the wrapper.
    kept = []
    for name in ("viewBox", "fill", "stroke", "preserveAspectRatio"):
        found = re.search(rf'\b{name}="([^"]*)"', attrs)
        if found:
            kept.append(f'{name}="{found.group(1)}"')

    ids = set(re.findall(r'\bid="([^"]+)"', body))
    for ident in sorted(ids, key=len, reverse=True):
        body = body.replace(f'id="{ident}"', f'id="{prefix}-{ident}"')
        body = body.replace(f"url(#{ident})", f"url(#{prefix}-{ident})")
        body = body.replace(f'href="#{ident}"', f'href="#{prefix}-{ident}"')

    body = "\n".join("    " + line.strip() for line in body.strip().splitlines() if line.strip())
    return " ".join(kept), body

light_attrs, light_body = load(os.environ["LIGHT"], "l")
dark_attrs, dark_body = load(os.environ["DARK"], "d")
viewbox = re.search(r'viewBox="([^"]*)"', light_attrs)
viewbox = viewbox.group(1) if viewbox else "0 0 24 24"

open(os.environ["OUT"], "w", encoding="utf-8").write(f"""<!--
  GENERATED by scripts/update-tile-icons.sh — do not edit.

  {os.environ['NAME']}, from {os.environ['SOURCE']}: its default drawing and its
  {os.environ['VARIANT']} variant in one file, switched by the viewer's colour
  scheme. Homepage renders a tile icon as an <img>, so the file has to decide
  this for itself.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}" role="img" aria-label="{os.environ['NAME']}">
  <style>
    .on-dark {{ display: none; }}
    @media (prefers-color-scheme: dark) {{
      .on-light {{ display: none; }}
      .on-dark {{ display: inline; }}
    }}
  </style>
  <svg class="on-light" {light_attrs}>
{light_body}
  </svg>
  <svg class="on-dark" {dark_attrs}>
{dark_body}
  </svg>
</svg>
""")
